/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleChangelogRouteImport } from './routes/$locale/changelog'
import { Route as LocaleDocsRouteImport } from './routes/$locale/docs'
import { Route as LocaleExamplesRouteImport } from './routes/$locale/examples'
import { Route as LocalePluginsIndexRouteImport } from './routes/$locale/plugins/index'
import { Route as LocalePluginsSlugRouteImport } from './routes/$locale/plugins/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChangelogRoute = LocaleChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDocsRoute = LocaleDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleExamplesRoute = LocaleExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePluginsIndexRoute = LocalePluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePluginsSlugRoute = LocalePluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/plugins/': typeof LocalePluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/plugins': typeof LocalePluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/docs': typeof LocaleDocsRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/plugins/': typeof LocalePluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/changelog'
    | '/$locale/docs'
    | '/$locale/examples'
    | '/$locale/'
    | '/$locale/plugins/$slug'
    | '/$locale/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/changelog'
    | '/$locale/docs'
    | '/$locale/examples'
    | '/$locale'
    | '/$locale/plugins/$slug'
    | '/$locale/plugins'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/changelog'
    | '/$locale/docs'
    | '/$locale/examples'
    | '/$locale/'
    | '/$locale/plugins/$slug'
    | '/$locale/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/changelog': {
      id: '/$locale/changelog'
      path: '/changelog'
      fullPath: '/$locale/changelog'
      preLoaderRoute: typeof LocaleChangelogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/docs': {
      id: '/$locale/docs'
      path: '/docs'
      fullPath: '/$locale/docs'
      preLoaderRoute: typeof LocaleDocsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/examples': {
      id: '/$locale/examples'
      path: '/examples'
      fullPath: '/$locale/examples'
      preLoaderRoute: typeof LocaleExamplesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plugins/': {
      id: '/$locale/plugins/'
      path: '/plugins'
      fullPath: '/$locale/plugins/'
      preLoaderRoute: typeof LocalePluginsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plugins/$slug': {
      id: '/$locale/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/$locale/plugins/$slug'
      preLoaderRoute: typeof LocalePluginsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleChangelogRoute: typeof LocaleChangelogRoute
  LocaleDocsRoute: typeof LocaleDocsRoute
  LocaleExamplesRoute: typeof LocaleExamplesRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePluginsSlugRoute: typeof LocalePluginsSlugRoute
  LocalePluginsIndexRoute: typeof LocalePluginsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleChangelogRoute: LocaleChangelogRoute,
  LocaleDocsRoute: LocaleDocsRoute,
  LocaleExamplesRoute: LocaleExamplesRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePluginsSlugRoute: LocalePluginsSlugRoute,
  LocalePluginsIndexRoute: LocalePluginsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
