/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as ApiDocsDotmdRouteImport } from './routes/api-docs[.]md'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleExamplesRouteImport } from './routes/$locale/examples'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiGithubStarsRouteImport } from './routes/api/github-stars'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LocaleAccountIndexRouteImport } from './routes/$locale/account/index'
import { Route as LocaleAccountAppealsRouteImport } from './routes/$locale/account/appeals'
import { Route as LocaleAccountCollectionsRouteImport } from './routes/$locale/account/collections'
import { Route as LocaleAccountNotificationsRouteImport } from './routes/$locale/account/notifications'
import { Route as LocaleAccountSettingsRouteImport } from './routes/$locale/account/settings'
import { Route as LocaleAccountSubmissionsRouteImport } from './routes/$locale/account/submissions'
import { Route as LocaleAuthCliRouteImport } from './routes/$locale/auth/cli'
import { Route as LocaleCategoriesSlugRouteImport } from './routes/$locale/categories/$slug'
import { Route as LocaleCollectionsIdRouteImport } from './routes/$locale/collections/$id'
import { Route as LocaleDocsIndexRouteImport } from './routes/$locale/docs/index'
import { Route as LocaleDocsSlugRouteImport } from './routes/$locale/docs/$slug'
import { Route as LocaleLegalDocumentRouteImport } from './routes/$locale/legal/$document'
import { Route as LocaleOperationsIndexRouteImport } from './routes/$locale/operations/index'
import { Route as LocalePluginsIndexRouteImport } from './routes/$locale/plugins/index'
import { Route as LocalePluginsSlugRouteImport } from './routes/$locale/plugins/$slug'
import { Route as LocalePublishersLoginRouteImport } from './routes/$locale/publishers/$login'
import { Route as LocaleUsersLoginRouteImport } from './routes/$locale/users/$login'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as AdminApprovalsIndexRouteImport } from './routes/admin/approvals/index'
import { Route as AdminApprovalsIdRouteImport } from './routes/admin/approvals/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCliTokenRouteImport } from './routes/api/cli/token'
import { Route as ApiCollectionsIdRouteImport } from './routes/api/collections/$id'
import { Route as ApiCommunityVerificationRouteImport } from './routes/api/community/verification'
import { Route as ApiMeAccountRouteImport } from './routes/api/me/account'
import { Route as ApiMeProfileRouteImport } from './routes/api/me/profile'
import { Route as ApiMeRelationshipsRouteImport } from './routes/api/me/relationships'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiPluginsIndexRouteImport } from './routes/api/plugins/index'
import { Route as ApiPluginsSlugRouteImport } from './routes/api/plugins/$slug'
import { Route as ApiPublishersLoginRouteImport } from './routes/api/publishers/$login'
import { Route as ApiRepliesIdRouteImport } from './routes/api/replies/$id'
import { Route as ApiReportsIndexRouteImport } from './routes/api/reports/index'
import { Route as ApiSubmissionsIndexRouteImport } from './routes/api/submissions/index'
import { Route as ApiUsersLoginRouteImport } from './routes/api/users/$login'
import { Route as ApiAdminApprovalsIndexRouteImport } from './routes/api/admin/approvals/index'
import { Route as ApiAdminApprovalsIdRouteImport } from './routes/api/admin/approvals/$id'
import { Route as ApiClaimsIdVerifyRouteImport } from './routes/api/claims/$id/verify'
import { Route as ApiCliAuthorizationsIndexRouteImport } from './routes/api/cli/authorizations/index'
import { Route as ApiMarketplacePluginsIndexRouteImport } from './routes/api/marketplace/plugins/index'
import { Route as ApiMarketplacePluginsSlugRouteImport } from './routes/api/marketplace/plugins/$slug'
import { Route as ApiMeAppealsIndexRouteImport } from './routes/api/me/appeals/index'
import { Route as ApiMeBlocksUserIdRouteImport } from './routes/api/me/blocks/$userId'
import { Route as ApiMeCollectionsIndexRouteImport } from './routes/api/me/collections/index'
import { Route as ApiMeCollectionsIdRouteImport } from './routes/api/me/collections/$id'
import { Route as ApiMeNotificationsIndexRouteImport } from './routes/api/me/notifications/index'
import { Route as ApiMeSubmissionsIndexRouteImport } from './routes/api/me/submissions/index'
import { Route as ApiOperationsReportsIndexRouteImport } from './routes/api/operations/reports/index'
import { Route as ApiOpsApprovalsIndexRouteImport } from './routes/api/ops/approvals/index'
import { Route as ApiOpsApprovalsIdRouteImport } from './routes/api/ops/approvals/$id'
import { Route as ApiOpsModerationActionsRouteImport } from './routes/api/ops/moderation/actions'
import { Route as ApiOpsModerationQueueRouteImport } from './routes/api/ops/moderation/queue'
import { Route as ApiOpsV1AuditRouteImport } from './routes/api/ops/v1/audit'
import { Route as ApiOpsV1ObservationsChar58batchRouteImport } from './routes/api/ops/v1/observations:batch'
import { Route as ApiOpsV1StatusRouteImport } from './routes/api/ops/v1/status'
import { Route as ApiPluginsSlugClaimsRouteImport } from './routes/api/plugins/$slug/claims'
import { Route as ApiPluginsSlugReviewRouteImport } from './routes/api/plugins/$slug/review'
import { Route as ApiPluginsSlugReviewsRouteImport } from './routes/api/plugins/$slug/reviews'
import { Route as ApiReviewsIdRepliesRouteImport } from './routes/api/reviews/$id/replies'
import { Route as OgHomeLocaleCardDotpngRouteImport } from './routes/og/home/$locale/card[.]png'
import { Route as ApiAdminApprovalsIdDecisionsRouteImport } from './routes/api/admin/approvals/$id/decisions'
import { Route as ApiCliAuthorizationsIdApproveRouteImport } from './routes/api/cli/authorizations/$id/approve'
import { Route as ApiMeNotificationsIdReadRouteImport } from './routes/api/me/notifications/$id/read'
import { Route as ApiMePluginsPluginIdBookmarkRouteImport } from './routes/api/me/plugins/$pluginId/bookmark'
import { Route as ApiMePluginsPluginIdFollowRouteImport } from './routes/api/me/plugins/$pluginId/follow'
import { Route as ApiMePublishersPublisherIdFollowRouteImport } from './routes/api/me/publishers/$publisherId/follow'
import { Route as ApiOpsApprovalsIdRevisionsRouteImport } from './routes/api/ops/approvals/$id/revisions'
import { Route as ApiOpsUsersIdRoleRouteImport } from './routes/api/ops/users/$id/role'
import { Route as ApiOpsV1ObservationsObservationIdRouteImport } from './routes/api/ops/v1/observations/$observationId'
import { Route as ApiOpsV1PluginsIndexRouteImport } from './routes/api/ops/v1/plugins/index'
import { Route as ApiOpsV1PluginsIdRouteImport } from './routes/api/ops/v1/plugins/$id'
import { Route as ApiOpsV1ReportsIndexRouteImport } from './routes/api/ops/v1/reports/index'
import { Route as ApiOpsV1SubmissionsIndexRouteImport } from './routes/api/ops/v1/submissions/index'
import { Route as ApiOpsV1SubmissionsIdRouteImport } from './routes/api/ops/v1/submissions/$id'
import { Route as OgPluginsLocaleSlugCardDotpngRouteImport } from './routes/og/plugins/$locale/$slug/card[.]png'
import { Route as ApiAdminApprovalsIdEffectsRetryRouteImport } from './routes/api/admin/approvals/$id/effects/retry'
import { Route as ApiMeCollectionsIdPluginsPluginIdRouteImport } from './routes/api/me/collections/$id/plugins/$pluginId'
import { Route as ApiOpsApprovalsIdEffectsClaimRouteImport } from './routes/api/ops/approvals/$id/effects/claim'
import { Route as ApiOpsApprovalsIdEffectsResultRouteImport } from './routes/api/ops/approvals/$id/effects/result'
import { Route as ApiOpsV1PluginsIdCurationRouteImport } from './routes/api/ops/v1/plugins/$id/curation'
import { Route as ApiOpsV1PluginsIdMediaRouteImport } from './routes/api/ops/v1/plugins/$id/media'
import { Route as ApiOpsV1PluginsIdVisibilityRouteImport } from './routes/api/ops/v1/plugins/$id/visibility'
import { Route as ApiOpsV1SubmissionsIdResolutionRouteImport } from './routes/api/ops/v1/submissions/$id/resolution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsDotmdRoute = ApiDocsDotmdRouteImport.update({
  id: '/api-docs.md',
  path: '/api-docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleExamplesRoute = LocaleExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => LocaleRoute,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStarsRoute = ApiGithubStarsRouteImport.update({
  id: '/api/github-stars',
  path: '/api/github-stars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAccountIndexRoute = LocaleAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountAppealsRoute = LocaleAccountAppealsRouteImport.update({
  id: '/account/appeals',
  path: '/account/appeals',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountCollectionsRoute =
  LocaleAccountCollectionsRouteImport.update({
    id: '/account/collections',
    path: '/account/collections',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAccountNotificationsRoute =
  LocaleAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAccountSettingsRoute = LocaleAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountSubmissionsRoute =
  LocaleAccountSubmissionsRouteImport.update({
    id: '/account/submissions',
    path: '/account/submissions',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAuthCliRoute = LocaleAuthCliRouteImport.update({
  id: '/auth/cli',
  path: '/auth/cli',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCategoriesSlugRoute = LocaleCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCollectionsIdRoute = LocaleCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDocsIndexRoute = LocaleDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDocsSlugRoute = LocaleDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLegalDocumentRoute = LocaleLegalDocumentRouteImport.update({
  id: '/legal/$document',
  path: '/legal/$document',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOperationsIndexRoute = LocaleOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePluginsIndexRoute = LocalePluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePluginsSlugRoute = LocalePluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePublishersLoginRoute = LocalePublishersLoginRouteImport.update({
  id: '/publishers/$login',
  path: '/publishers/$login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUsersLoginRoute = LocaleUsersLoginRouteImport.update({
  id: '/users/$login',
  path: '/users/$login',
  getParentRoute: () => LocaleRoute,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminApprovalsIndexRoute = AdminApprovalsIndexRouteImport.update({
  id: '/admin/approvals/',
  path: '/admin/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsIdRoute = AdminApprovalsIdRouteImport.update({
  id: '/admin/approvals/$id',
  path: '/admin/approvals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliTokenRoute = ApiCliTokenRouteImport.update({
  id: '/api/cli/token',
  path: '/api/cli/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsIdRoute = ApiCollectionsIdRouteImport.update({
  id: '/api/collections/$id',
  path: '/api/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityVerificationRoute =
  ApiCommunityVerificationRouteImport.update({
    id: '/api/community/verification',
    path: '/api/community/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeAccountRoute = ApiMeAccountRouteImport.update({
  id: '/api/me/account',
  path: '/api/me/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeProfileRoute = ApiMeProfileRouteImport.update({
  id: '/api/me/profile',
  path: '/api/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRelationshipsRoute = ApiMeRelationshipsRouteImport.update({
  id: '/api/me/relationships',
  path: '/api/me/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsIndexRoute = ApiPluginsIndexRouteImport.update({
  id: '/api/plugins/',
  path: '/api/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsSlugRoute = ApiPluginsSlugRouteImport.update({
  id: '/api/plugins/$slug',
  path: '/api/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishersLoginRoute = ApiPublishersLoginRouteImport.update({
  id: '/api/publishers/$login',
  path: '/api/publishers/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepliesIdRoute = ApiRepliesIdRouteImport.update({
  id: '/api/replies/$id',
  path: '/api/replies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIndexRoute = ApiReportsIndexRouteImport.update({
  id: '/api/reports/',
  path: '/api/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsIndexRoute = ApiSubmissionsIndexRouteImport.update({
  id: '/api/submissions/',
  path: '/api/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersLoginRoute = ApiUsersLoginRouteImport.update({
  id: '/api/users/$login',
  path: '/api/users/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApprovalsIndexRoute = ApiAdminApprovalsIndexRouteImport.update({
  id: '/api/admin/approvals/',
  path: '/api/admin/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApprovalsIdRoute = ApiAdminApprovalsIdRouteImport.update({
  id: '/api/admin/approvals/$id',
  path: '/api/admin/approvals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimsIdVerifyRoute = ApiClaimsIdVerifyRouteImport.update({
  id: '/api/claims/$id/verify',
  path: '/api/claims/$id/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthorizationsIndexRoute =
  ApiCliAuthorizationsIndexRouteImport.update({
    id: '/api/cli/authorizations/',
    path: '/api/cli/authorizations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketplacePluginsIndexRoute =
  ApiMarketplacePluginsIndexRouteImport.update({
    id: '/api/marketplace/plugins/',
    path: '/api/marketplace/plugins/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketplacePluginsSlugRoute =
  ApiMarketplacePluginsSlugRouteImport.update({
    id: '/api/marketplace/plugins/$slug',
    path: '/api/marketplace/plugins/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeAppealsIndexRoute = ApiMeAppealsIndexRouteImport.update({
  id: '/api/me/appeals/',
  path: '/api/me/appeals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBlocksUserIdRoute = ApiMeBlocksUserIdRouteImport.update({
  id: '/api/me/blocks/$userId',
  path: '/api/me/blocks/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeCollectionsIndexRoute = ApiMeCollectionsIndexRouteImport.update({
  id: '/api/me/collections/',
  path: '/api/me/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeCollectionsIdRoute = ApiMeCollectionsIdRouteImport.update({
  id: '/api/me/collections/$id',
  path: '/api/me/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeNotificationsIndexRoute = ApiMeNotificationsIndexRouteImport.update({
  id: '/api/me/notifications/',
  path: '/api/me/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeSubmissionsIndexRoute = ApiMeSubmissionsIndexRouteImport.update({
  id: '/api/me/submissions/',
  path: '/api/me/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsReportsIndexRoute =
  ApiOperationsReportsIndexRouteImport.update({
    id: '/api/operations/reports/',
    path: '/api/operations/reports/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsApprovalsIndexRoute = ApiOpsApprovalsIndexRouteImport.update({
  id: '/api/ops/approvals/',
  path: '/api/ops/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsApprovalsIdRoute = ApiOpsApprovalsIdRouteImport.update({
  id: '/api/ops/approvals/$id',
  path: '/api/ops/approvals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsModerationActionsRoute = ApiOpsModerationActionsRouteImport.update({
  id: '/api/ops/moderation/actions',
  path: '/api/ops/moderation/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsModerationQueueRoute = ApiOpsModerationQueueRouteImport.update({
  id: '/api/ops/moderation/queue',
  path: '/api/ops/moderation/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1AuditRoute = ApiOpsV1AuditRouteImport.update({
  id: '/api/ops/v1/audit',
  path: '/api/ops/v1/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1ObservationsChar58batchRoute =
  ApiOpsV1ObservationsChar58batchRouteImport.update({
    id: '/api/ops/v1/observations:batch',
    path: '/api/ops/v1/observations:batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsV1StatusRoute = ApiOpsV1StatusRouteImport.update({
  id: '/api/ops/v1/status',
  path: '/api/ops/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginsSlugClaimsRoute = ApiPluginsSlugClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => ApiPluginsSlugRoute,
} as any)
const ApiPluginsSlugReviewRoute = ApiPluginsSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ApiPluginsSlugRoute,
} as any)
const ApiPluginsSlugReviewsRoute = ApiPluginsSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ApiPluginsSlugRoute,
} as any)
const ApiReviewsIdRepliesRoute = ApiReviewsIdRepliesRouteImport.update({
  id: '/api/reviews/$id/replies',
  path: '/api/reviews/$id/replies',
  getParentRoute: () => rootRouteImport,
} as any)
const OgHomeLocaleCardDotpngRoute = OgHomeLocaleCardDotpngRouteImport.update({
  id: '/og/home/$locale/card.png',
  path: '/og/home/$locale/card.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApprovalsIdDecisionsRoute =
  ApiAdminApprovalsIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => ApiAdminApprovalsIdRoute,
  } as any)
const ApiCliAuthorizationsIdApproveRoute =
  ApiCliAuthorizationsIdApproveRouteImport.update({
    id: '/api/cli/authorizations/$id/approve',
    path: '/api/cli/authorizations/$id/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeNotificationsIdReadRoute =
  ApiMeNotificationsIdReadRouteImport.update({
    id: '/api/me/notifications/$id/read',
    path: '/api/me/notifications/$id/read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMePluginsPluginIdBookmarkRoute =
  ApiMePluginsPluginIdBookmarkRouteImport.update({
    id: '/api/me/plugins/$pluginId/bookmark',
    path: '/api/me/plugins/$pluginId/bookmark',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMePluginsPluginIdFollowRoute =
  ApiMePluginsPluginIdFollowRouteImport.update({
    id: '/api/me/plugins/$pluginId/follow',
    path: '/api/me/plugins/$pluginId/follow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMePublishersPublisherIdFollowRoute =
  ApiMePublishersPublisherIdFollowRouteImport.update({
    id: '/api/me/publishers/$publisherId/follow',
    path: '/api/me/publishers/$publisherId/follow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsApprovalsIdRevisionsRoute =
  ApiOpsApprovalsIdRevisionsRouteImport.update({
    id: '/revisions',
    path: '/revisions',
    getParentRoute: () => ApiOpsApprovalsIdRoute,
  } as any)
const ApiOpsUsersIdRoleRoute = ApiOpsUsersIdRoleRouteImport.update({
  id: '/api/ops/users/$id/role',
  path: '/api/ops/users/$id/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1ObservationsObservationIdRoute =
  ApiOpsV1ObservationsObservationIdRouteImport.update({
    id: '/api/ops/v1/observations/$observationId',
    path: '/api/ops/v1/observations/$observationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsV1PluginsIndexRoute = ApiOpsV1PluginsIndexRouteImport.update({
  id: '/api/ops/v1/plugins/',
  path: '/api/ops/v1/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1PluginsIdRoute = ApiOpsV1PluginsIdRouteImport.update({
  id: '/api/ops/v1/plugins/$id',
  path: '/api/ops/v1/plugins/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1ReportsIndexRoute = ApiOpsV1ReportsIndexRouteImport.update({
  id: '/api/ops/v1/reports/',
  path: '/api/ops/v1/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsV1SubmissionsIndexRoute =
  ApiOpsV1SubmissionsIndexRouteImport.update({
    id: '/api/ops/v1/submissions/',
    path: '/api/ops/v1/submissions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsV1SubmissionsIdRoute = ApiOpsV1SubmissionsIdRouteImport.update({
  id: '/api/ops/v1/submissions/$id',
  path: '/api/ops/v1/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPluginsLocaleSlugCardDotpngRoute =
  OgPluginsLocaleSlugCardDotpngRouteImport.update({
    id: '/og/plugins/$locale/$slug/card.png',
    path: '/og/plugins/$locale/$slug/card.png',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminApprovalsIdEffectsRetryRoute =
  ApiAdminApprovalsIdEffectsRetryRouteImport.update({
    id: '/effects/retry',
    path: '/effects/retry',
    getParentRoute: () => ApiAdminApprovalsIdRoute,
  } as any)
const ApiMeCollectionsIdPluginsPluginIdRoute =
  ApiMeCollectionsIdPluginsPluginIdRouteImport.update({
    id: '/plugins/$pluginId',
    path: '/plugins/$pluginId',
    getParentRoute: () => ApiMeCollectionsIdRoute,
  } as any)
const ApiOpsApprovalsIdEffectsClaimRoute =
  ApiOpsApprovalsIdEffectsClaimRouteImport.update({
    id: '/effects/claim',
    path: '/effects/claim',
    getParentRoute: () => ApiOpsApprovalsIdRoute,
  } as any)
const ApiOpsApprovalsIdEffectsResultRoute =
  ApiOpsApprovalsIdEffectsResultRouteImport.update({
    id: '/effects/result',
    path: '/effects/result',
    getParentRoute: () => ApiOpsApprovalsIdRoute,
  } as any)
const ApiOpsV1PluginsIdCurationRoute =
  ApiOpsV1PluginsIdCurationRouteImport.update({
    id: '/curation',
    path: '/curation',
    getParentRoute: () => ApiOpsV1PluginsIdRoute,
  } as any)
const ApiOpsV1PluginsIdMediaRoute = ApiOpsV1PluginsIdMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ApiOpsV1PluginsIdRoute,
} as any)
const ApiOpsV1PluginsIdVisibilityRoute =
  ApiOpsV1PluginsIdVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => ApiOpsV1PluginsIdRoute,
  } as any)
const ApiOpsV1SubmissionsIdResolutionRoute =
  ApiOpsV1SubmissionsIdResolutionRouteImport.update({
    id: '/resolution',
    path: '/resolution',
    getParentRoute: () => ApiOpsV1SubmissionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/api-docs.md': typeof ApiDocsDotmdRoute
  '/auth.md': typeof AuthDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/account/appeals': typeof LocaleAccountAppealsRoute
  '/$locale/account/collections': typeof LocaleAccountCollectionsRoute
  '/$locale/account/notifications': typeof LocaleAccountNotificationsRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/account/submissions': typeof LocaleAccountSubmissionsRoute
  '/$locale/auth/cli': typeof LocaleAuthCliRoute
  '/$locale/categories/$slug': typeof LocaleCategoriesSlugRoute
  '/$locale/collections/$id': typeof LocaleCollectionsIdRoute
  '/$locale/docs/$slug': typeof LocaleDocsSlugRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/publishers/$login': typeof LocalePublishersLoginRoute
  '/$locale/users/$login': typeof LocaleUsersLoginRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/admin/approvals/$id': typeof AdminApprovalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/token': typeof ApiCliTokenRoute
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/community/verification': typeof ApiCommunityVerificationRoute
  '/api/me/account': typeof ApiMeAccountRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/me/relationships': typeof ApiMeRelationshipsRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/plugins/$slug': typeof ApiPluginsSlugRouteWithChildren
  '/api/publishers/$login': typeof ApiPublishersLoginRoute
  '/api/replies/$id': typeof ApiRepliesIdRoute
  '/api/users/$login': typeof ApiUsersLoginRoute
  '/$locale/account/': typeof LocaleAccountIndexRoute
  '/$locale/docs/': typeof LocaleDocsIndexRoute
  '/$locale/operations/': typeof LocaleOperationsIndexRoute
  '/$locale/plugins/': typeof LocalePluginsIndexRoute
  '/admin/approvals/': typeof AdminApprovalsIndexRoute
  '/api/plugins/': typeof ApiPluginsIndexRoute
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/approvals/$id': typeof ApiAdminApprovalsIdRouteWithChildren
  '/api/claims/$id/verify': typeof ApiClaimsIdVerifyRoute
  '/api/marketplace/plugins/$slug': typeof ApiMarketplacePluginsSlugRoute
  '/api/me/blocks/$userId': typeof ApiMeBlocksUserIdRoute
  '/api/me/collections/$id': typeof ApiMeCollectionsIdRouteWithChildren
  '/api/ops/approvals/$id': typeof ApiOpsApprovalsIdRouteWithChildren
  '/api/ops/moderation/actions': typeof ApiOpsModerationActionsRoute
  '/api/ops/moderation/queue': typeof ApiOpsModerationQueueRoute
  '/api/ops/v1/audit': typeof ApiOpsV1AuditRoute
  '/api/ops/v1/observations:batch': typeof ApiOpsV1ObservationsChar58batchRoute
  '/api/ops/v1/status': typeof ApiOpsV1StatusRoute
  '/api/plugins/$slug/claims': typeof ApiPluginsSlugClaimsRoute
  '/api/plugins/$slug/review': typeof ApiPluginsSlugReviewRoute
  '/api/plugins/$slug/reviews': typeof ApiPluginsSlugReviewsRoute
  '/api/reviews/$id/replies': typeof ApiReviewsIdRepliesRoute
  '/og/home/$locale/card.png': typeof OgHomeLocaleCardDotpngRoute
  '/api/admin/approvals/': typeof ApiAdminApprovalsIndexRoute
  '/api/cli/authorizations/': typeof ApiCliAuthorizationsIndexRoute
  '/api/marketplace/plugins/': typeof ApiMarketplacePluginsIndexRoute
  '/api/me/appeals/': typeof ApiMeAppealsIndexRoute
  '/api/me/collections/': typeof ApiMeCollectionsIndexRoute
  '/api/me/notifications/': typeof ApiMeNotificationsIndexRoute
  '/api/me/submissions/': typeof ApiMeSubmissionsIndexRoute
  '/api/operations/reports/': typeof ApiOperationsReportsIndexRoute
  '/api/ops/approvals/': typeof ApiOpsApprovalsIndexRoute
  '/api/admin/approvals/$id/decisions': typeof ApiAdminApprovalsIdDecisionsRoute
  '/api/cli/authorizations/$id/approve': typeof ApiCliAuthorizationsIdApproveRoute
  '/api/me/notifications/$id/read': typeof ApiMeNotificationsIdReadRoute
  '/api/me/plugins/$pluginId/bookmark': typeof ApiMePluginsPluginIdBookmarkRoute
  '/api/me/plugins/$pluginId/follow': typeof ApiMePluginsPluginIdFollowRoute
  '/api/me/publishers/$publisherId/follow': typeof ApiMePublishersPublisherIdFollowRoute
  '/api/ops/approvals/$id/revisions': typeof ApiOpsApprovalsIdRevisionsRoute
  '/api/ops/users/$id/role': typeof ApiOpsUsersIdRoleRoute
  '/api/ops/v1/observations/$observationId': typeof ApiOpsV1ObservationsObservationIdRoute
  '/api/ops/v1/plugins/$id': typeof ApiOpsV1PluginsIdRouteWithChildren
  '/api/ops/v1/submissions/$id': typeof ApiOpsV1SubmissionsIdRouteWithChildren
  '/og/plugins/$locale/$slug/card.png': typeof OgPluginsLocaleSlugCardDotpngRoute
  '/api/ops/v1/plugins/': typeof ApiOpsV1PluginsIndexRoute
  '/api/ops/v1/reports/': typeof ApiOpsV1ReportsIndexRoute
  '/api/ops/v1/submissions/': typeof ApiOpsV1SubmissionsIndexRoute
  '/api/admin/approvals/$id/effects/retry': typeof ApiAdminApprovalsIdEffectsRetryRoute
  '/api/me/collections/$id/plugins/$pluginId': typeof ApiMeCollectionsIdPluginsPluginIdRoute
  '/api/ops/approvals/$id/effects/claim': typeof ApiOpsApprovalsIdEffectsClaimRoute
  '/api/ops/approvals/$id/effects/result': typeof ApiOpsApprovalsIdEffectsResultRoute
  '/api/ops/v1/plugins/$id/curation': typeof ApiOpsV1PluginsIdCurationRoute
  '/api/ops/v1/plugins/$id/media': typeof ApiOpsV1PluginsIdMediaRoute
  '/api/ops/v1/plugins/$id/visibility': typeof ApiOpsV1PluginsIdVisibilityRoute
  '/api/ops/v1/submissions/$id/resolution': typeof ApiOpsV1SubmissionsIdResolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs.md': typeof ApiDocsDotmdRoute
  '/auth.md': typeof AuthDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/account/appeals': typeof LocaleAccountAppealsRoute
  '/$locale/account/collections': typeof LocaleAccountCollectionsRoute
  '/$locale/account/notifications': typeof LocaleAccountNotificationsRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/account/submissions': typeof LocaleAccountSubmissionsRoute
  '/$locale/auth/cli': typeof LocaleAuthCliRoute
  '/$locale/categories/$slug': typeof LocaleCategoriesSlugRoute
  '/$locale/collections/$id': typeof LocaleCollectionsIdRoute
  '/$locale/docs/$slug': typeof LocaleDocsSlugRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/publishers/$login': typeof LocalePublishersLoginRoute
  '/$locale/users/$login': typeof LocaleUsersLoginRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/admin/approvals/$id': typeof AdminApprovalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/token': typeof ApiCliTokenRoute
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/community/verification': typeof ApiCommunityVerificationRoute
  '/api/me/account': typeof ApiMeAccountRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/me/relationships': typeof ApiMeRelationshipsRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/plugins/$slug': typeof ApiPluginsSlugRouteWithChildren
  '/api/publishers/$login': typeof ApiPublishersLoginRoute
  '/api/replies/$id': typeof ApiRepliesIdRoute
  '/api/users/$login': typeof ApiUsersLoginRoute
  '/$locale/account': typeof LocaleAccountIndexRoute
  '/$locale/docs': typeof LocaleDocsIndexRoute
  '/$locale/operations': typeof LocaleOperationsIndexRoute
  '/$locale/plugins': typeof LocalePluginsIndexRoute
  '/admin/approvals': typeof AdminApprovalsIndexRoute
  '/api/plugins': typeof ApiPluginsIndexRoute
  '/api/reports': typeof ApiReportsIndexRoute
  '/api/submissions': typeof ApiSubmissionsIndexRoute
  '/api/admin/approvals/$id': typeof ApiAdminApprovalsIdRouteWithChildren
  '/api/claims/$id/verify': typeof ApiClaimsIdVerifyRoute
  '/api/marketplace/plugins/$slug': typeof ApiMarketplacePluginsSlugRoute
  '/api/me/blocks/$userId': typeof ApiMeBlocksUserIdRoute
  '/api/me/collections/$id': typeof ApiMeCollectionsIdRouteWithChildren
  '/api/ops/approvals/$id': typeof ApiOpsApprovalsIdRouteWithChildren
  '/api/ops/moderation/actions': typeof ApiOpsModerationActionsRoute
  '/api/ops/moderation/queue': typeof ApiOpsModerationQueueRoute
  '/api/ops/v1/audit': typeof ApiOpsV1AuditRoute
  '/api/ops/v1/observations:batch': typeof ApiOpsV1ObservationsChar58batchRoute
  '/api/ops/v1/status': typeof ApiOpsV1StatusRoute
  '/api/plugins/$slug/claims': typeof ApiPluginsSlugClaimsRoute
  '/api/plugins/$slug/review': typeof ApiPluginsSlugReviewRoute
  '/api/plugins/$slug/reviews': typeof ApiPluginsSlugReviewsRoute
  '/api/reviews/$id/replies': typeof ApiReviewsIdRepliesRoute
  '/og/home/$locale/card.png': typeof OgHomeLocaleCardDotpngRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsIndexRoute
  '/api/cli/authorizations': typeof ApiCliAuthorizationsIndexRoute
  '/api/marketplace/plugins': typeof ApiMarketplacePluginsIndexRoute
  '/api/me/appeals': typeof ApiMeAppealsIndexRoute
  '/api/me/collections': typeof ApiMeCollectionsIndexRoute
  '/api/me/notifications': typeof ApiMeNotificationsIndexRoute
  '/api/me/submissions': typeof ApiMeSubmissionsIndexRoute
  '/api/operations/reports': typeof ApiOperationsReportsIndexRoute
  '/api/ops/approvals': typeof ApiOpsApprovalsIndexRoute
  '/api/admin/approvals/$id/decisions': typeof ApiAdminApprovalsIdDecisionsRoute
  '/api/cli/authorizations/$id/approve': typeof ApiCliAuthorizationsIdApproveRoute
  '/api/me/notifications/$id/read': typeof ApiMeNotificationsIdReadRoute
  '/api/me/plugins/$pluginId/bookmark': typeof ApiMePluginsPluginIdBookmarkRoute
  '/api/me/plugins/$pluginId/follow': typeof ApiMePluginsPluginIdFollowRoute
  '/api/me/publishers/$publisherId/follow': typeof ApiMePublishersPublisherIdFollowRoute
  '/api/ops/approvals/$id/revisions': typeof ApiOpsApprovalsIdRevisionsRoute
  '/api/ops/users/$id/role': typeof ApiOpsUsersIdRoleRoute
  '/api/ops/v1/observations/$observationId': typeof ApiOpsV1ObservationsObservationIdRoute
  '/api/ops/v1/plugins/$id': typeof ApiOpsV1PluginsIdRouteWithChildren
  '/api/ops/v1/submissions/$id': typeof ApiOpsV1SubmissionsIdRouteWithChildren
  '/og/plugins/$locale/$slug/card.png': typeof OgPluginsLocaleSlugCardDotpngRoute
  '/api/ops/v1/plugins': typeof ApiOpsV1PluginsIndexRoute
  '/api/ops/v1/reports': typeof ApiOpsV1ReportsIndexRoute
  '/api/ops/v1/submissions': typeof ApiOpsV1SubmissionsIndexRoute
  '/api/admin/approvals/$id/effects/retry': typeof ApiAdminApprovalsIdEffectsRetryRoute
  '/api/me/collections/$id/plugins/$pluginId': typeof ApiMeCollectionsIdPluginsPluginIdRoute
  '/api/ops/approvals/$id/effects/claim': typeof ApiOpsApprovalsIdEffectsClaimRoute
  '/api/ops/approvals/$id/effects/result': typeof ApiOpsApprovalsIdEffectsResultRoute
  '/api/ops/v1/plugins/$id/curation': typeof ApiOpsV1PluginsIdCurationRoute
  '/api/ops/v1/plugins/$id/media': typeof ApiOpsV1PluginsIdMediaRoute
  '/api/ops/v1/plugins/$id/visibility': typeof ApiOpsV1PluginsIdVisibilityRoute
  '/api/ops/v1/submissions/$id/resolution': typeof ApiOpsV1SubmissionsIdResolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/api-docs.md': typeof ApiDocsDotmdRoute
  '/auth.md': typeof AuthDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/examples': typeof LocaleExamplesRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/github-stars': typeof ApiGithubStarsRoute
  '/api/health': typeof ApiHealthRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/account/appeals': typeof LocaleAccountAppealsRoute
  '/$locale/account/collections': typeof LocaleAccountCollectionsRoute
  '/$locale/account/notifications': typeof LocaleAccountNotificationsRoute
  '/$locale/account/settings': typeof LocaleAccountSettingsRoute
  '/$locale/account/submissions': typeof LocaleAccountSubmissionsRoute
  '/$locale/auth/cli': typeof LocaleAuthCliRoute
  '/$locale/categories/$slug': typeof LocaleCategoriesSlugRoute
  '/$locale/collections/$id': typeof LocaleCollectionsIdRoute
  '/$locale/docs/$slug': typeof LocaleDocsSlugRoute
  '/$locale/legal/$document': typeof LocaleLegalDocumentRoute
  '/$locale/plugins/$slug': typeof LocalePluginsSlugRoute
  '/$locale/publishers/$login': typeof LocalePublishersLoginRoute
  '/$locale/users/$login': typeof LocaleUsersLoginRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/admin/approvals/$id': typeof AdminApprovalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/token': typeof ApiCliTokenRoute
  '/api/collections/$id': typeof ApiCollectionsIdRoute
  '/api/community/verification': typeof ApiCommunityVerificationRoute
  '/api/me/account': typeof ApiMeAccountRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/me/relationships': typeof ApiMeRelationshipsRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/plugins/$slug': typeof ApiPluginsSlugRouteWithChildren
  '/api/publishers/$login': typeof ApiPublishersLoginRoute
  '/api/replies/$id': typeof ApiRepliesIdRoute
  '/api/users/$login': typeof ApiUsersLoginRoute
  '/$locale/account/': typeof LocaleAccountIndexRoute
  '/$locale/docs/': typeof LocaleDocsIndexRoute
  '/$locale/operations/': typeof LocaleOperationsIndexRoute
  '/$locale/plugins/': typeof LocalePluginsIndexRoute
  '/admin/approvals/': typeof AdminApprovalsIndexRoute
  '/api/plugins/': typeof ApiPluginsIndexRoute
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/submissions/': typeof ApiSubmissionsIndexRoute
  '/api/admin/approvals/$id': typeof ApiAdminApprovalsIdRouteWithChildren
  '/api/claims/$id/verify': typeof ApiClaimsIdVerifyRoute
  '/api/marketplace/plugins/$slug': typeof ApiMarketplacePluginsSlugRoute
  '/api/me/blocks/$userId': typeof ApiMeBlocksUserIdRoute
  '/api/me/collections/$id': typeof ApiMeCollectionsIdRouteWithChildren
  '/api/ops/approvals/$id': typeof ApiOpsApprovalsIdRouteWithChildren
  '/api/ops/moderation/actions': typeof ApiOpsModerationActionsRoute
  '/api/ops/moderation/queue': typeof ApiOpsModerationQueueRoute
  '/api/ops/v1/audit': typeof ApiOpsV1AuditRoute
  '/api/ops/v1/observations:batch': typeof ApiOpsV1ObservationsChar58batchRoute
  '/api/ops/v1/status': typeof ApiOpsV1StatusRoute
  '/api/plugins/$slug/claims': typeof ApiPluginsSlugClaimsRoute
  '/api/plugins/$slug/review': typeof ApiPluginsSlugReviewRoute
  '/api/plugins/$slug/reviews': typeof ApiPluginsSlugReviewsRoute
  '/api/reviews/$id/replies': typeof ApiReviewsIdRepliesRoute
  '/og/home/$locale/card.png': typeof OgHomeLocaleCardDotpngRoute
  '/api/admin/approvals/': typeof ApiAdminApprovalsIndexRoute
  '/api/cli/authorizations/': typeof ApiCliAuthorizationsIndexRoute
  '/api/marketplace/plugins/': typeof ApiMarketplacePluginsIndexRoute
  '/api/me/appeals/': typeof ApiMeAppealsIndexRoute
  '/api/me/collections/': typeof ApiMeCollectionsIndexRoute
  '/api/me/notifications/': typeof ApiMeNotificationsIndexRoute
  '/api/me/submissions/': typeof ApiMeSubmissionsIndexRoute
  '/api/operations/reports/': typeof ApiOperationsReportsIndexRoute
  '/api/ops/approvals/': typeof ApiOpsApprovalsIndexRoute
  '/api/admin/approvals/$id/decisions': typeof ApiAdminApprovalsIdDecisionsRoute
  '/api/cli/authorizations/$id/approve': typeof ApiCliAuthorizationsIdApproveRoute
  '/api/me/notifications/$id/read': typeof ApiMeNotificationsIdReadRoute
  '/api/me/plugins/$pluginId/bookmark': typeof ApiMePluginsPluginIdBookmarkRoute
  '/api/me/plugins/$pluginId/follow': typeof ApiMePluginsPluginIdFollowRoute
  '/api/me/publishers/$publisherId/follow': typeof ApiMePublishersPublisherIdFollowRoute
  '/api/ops/approvals/$id/revisions': typeof ApiOpsApprovalsIdRevisionsRoute
  '/api/ops/users/$id/role': typeof ApiOpsUsersIdRoleRoute
  '/api/ops/v1/observations/$observationId': typeof ApiOpsV1ObservationsObservationIdRoute
  '/api/ops/v1/plugins/$id': typeof ApiOpsV1PluginsIdRouteWithChildren
  '/api/ops/v1/submissions/$id': typeof ApiOpsV1SubmissionsIdRouteWithChildren
  '/og/plugins/$locale/$slug/card.png': typeof OgPluginsLocaleSlugCardDotpngRoute
  '/api/ops/v1/plugins/': typeof ApiOpsV1PluginsIndexRoute
  '/api/ops/v1/reports/': typeof ApiOpsV1ReportsIndexRoute
  '/api/ops/v1/submissions/': typeof ApiOpsV1SubmissionsIndexRoute
  '/api/admin/approvals/$id/effects/retry': typeof ApiAdminApprovalsIdEffectsRetryRoute
  '/api/me/collections/$id/plugins/$pluginId': typeof ApiMeCollectionsIdPluginsPluginIdRoute
  '/api/ops/approvals/$id/effects/claim': typeof ApiOpsApprovalsIdEffectsClaimRoute
  '/api/ops/approvals/$id/effects/result': typeof ApiOpsApprovalsIdEffectsResultRoute
  '/api/ops/v1/plugins/$id/curation': typeof ApiOpsV1PluginsIdCurationRoute
  '/api/ops/v1/plugins/$id/media': typeof ApiOpsV1PluginsIdMediaRoute
  '/api/ops/v1/plugins/$id/visibility': typeof ApiOpsV1PluginsIdVisibilityRoute
  '/api/ops/v1/submissions/$id/resolution': typeof ApiOpsV1SubmissionsIdResolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/api-docs.md'
    | '/auth.md'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/examples'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/github-stars'
    | '/api/health'
    | '/$locale/'
    | '/$locale/account/appeals'
    | '/$locale/account/collections'
    | '/$locale/account/notifications'
    | '/$locale/account/settings'
    | '/$locale/account/submissions'
    | '/$locale/auth/cli'
    | '/$locale/categories/$slug'
    | '/$locale/collections/$id'
    | '/$locale/docs/$slug'
    | '/$locale/legal/$document'
    | '/$locale/plugins/$slug'
    | '/$locale/publishers/$login'
    | '/$locale/users/$login'
    | '/.well-known/mcp/server-card.json'
    | '/admin/approvals/$id'
    | '/api/auth/$'
    | '/api/cli/token'
    | '/api/collections/$id'
    | '/api/community/verification'
    | '/api/me/account'
    | '/api/me/profile'
    | '/api/me/relationships'
    | '/api/media/$id'
    | '/api/plugins/$slug'
    | '/api/publishers/$login'
    | '/api/replies/$id'
    | '/api/users/$login'
    | '/$locale/account/'
    | '/$locale/docs/'
    | '/$locale/operations/'
    | '/$locale/plugins/'
    | '/admin/approvals/'
    | '/api/plugins/'
    | '/api/reports/'
    | '/api/submissions/'
    | '/api/admin/approvals/$id'
    | '/api/claims/$id/verify'
    | '/api/marketplace/plugins/$slug'
    | '/api/me/blocks/$userId'
    | '/api/me/collections/$id'
    | '/api/ops/approvals/$id'
    | '/api/ops/moderation/actions'
    | '/api/ops/moderation/queue'
    | '/api/ops/v1/audit'
    | '/api/ops/v1/observations:batch'
    | '/api/ops/v1/status'
    | '/api/plugins/$slug/claims'
    | '/api/plugins/$slug/review'
    | '/api/plugins/$slug/reviews'
    | '/api/reviews/$id/replies'
    | '/og/home/$locale/card.png'
    | '/api/admin/approvals/'
    | '/api/cli/authorizations/'
    | '/api/marketplace/plugins/'
    | '/api/me/appeals/'
    | '/api/me/collections/'
    | '/api/me/notifications/'
    | '/api/me/submissions/'
    | '/api/operations/reports/'
    | '/api/ops/approvals/'
    | '/api/admin/approvals/$id/decisions'
    | '/api/cli/authorizations/$id/approve'
    | '/api/me/notifications/$id/read'
    | '/api/me/plugins/$pluginId/bookmark'
    | '/api/me/plugins/$pluginId/follow'
    | '/api/me/publishers/$publisherId/follow'
    | '/api/ops/approvals/$id/revisions'
    | '/api/ops/users/$id/role'
    | '/api/ops/v1/observations/$observationId'
    | '/api/ops/v1/plugins/$id'
    | '/api/ops/v1/submissions/$id'
    | '/og/plugins/$locale/$slug/card.png'
    | '/api/ops/v1/plugins/'
    | '/api/ops/v1/reports/'
    | '/api/ops/v1/submissions/'
    | '/api/admin/approvals/$id/effects/retry'
    | '/api/me/collections/$id/plugins/$pluginId'
    | '/api/ops/approvals/$id/effects/claim'
    | '/api/ops/approvals/$id/effects/result'
    | '/api/ops/v1/plugins/$id/curation'
    | '/api/ops/v1/plugins/$id/media'
    | '/api/ops/v1/plugins/$id/visibility'
    | '/api/ops/v1/submissions/$id/resolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs.md'
    | '/auth.md'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/examples'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/github-stars'
    | '/api/health'
    | '/$locale'
    | '/$locale/account/appeals'
    | '/$locale/account/collections'
    | '/$locale/account/notifications'
    | '/$locale/account/settings'
    | '/$locale/account/submissions'
    | '/$locale/auth/cli'
    | '/$locale/categories/$slug'
    | '/$locale/collections/$id'
    | '/$locale/docs/$slug'
    | '/$locale/legal/$document'
    | '/$locale/plugins/$slug'
    | '/$locale/publishers/$login'
    | '/$locale/users/$login'
    | '/.well-known/mcp/server-card.json'
    | '/admin/approvals/$id'
    | '/api/auth/$'
    | '/api/cli/token'
    | '/api/collections/$id'
    | '/api/community/verification'
    | '/api/me/account'
    | '/api/me/profile'
    | '/api/me/relationships'
    | '/api/media/$id'
    | '/api/plugins/$slug'
    | '/api/publishers/$login'
    | '/api/replies/$id'
    | '/api/users/$login'
    | '/$locale/account'
    | '/$locale/docs'
    | '/$locale/operations'
    | '/$locale/plugins'
    | '/admin/approvals'
    | '/api/plugins'
    | '/api/reports'
    | '/api/submissions'
    | '/api/admin/approvals/$id'
    | '/api/claims/$id/verify'
    | '/api/marketplace/plugins/$slug'
    | '/api/me/blocks/$userId'
    | '/api/me/collections/$id'
    | '/api/ops/approvals/$id'
    | '/api/ops/moderation/actions'
    | '/api/ops/moderation/queue'
    | '/api/ops/v1/audit'
    | '/api/ops/v1/observations:batch'
    | '/api/ops/v1/status'
    | '/api/plugins/$slug/claims'
    | '/api/plugins/$slug/review'
    | '/api/plugins/$slug/reviews'
    | '/api/reviews/$id/replies'
    | '/og/home/$locale/card.png'
    | '/api/admin/approvals'
    | '/api/cli/authorizations'
    | '/api/marketplace/plugins'
    | '/api/me/appeals'
    | '/api/me/collections'
    | '/api/me/notifications'
    | '/api/me/submissions'
    | '/api/operations/reports'
    | '/api/ops/approvals'
    | '/api/admin/approvals/$id/decisions'
    | '/api/cli/authorizations/$id/approve'
    | '/api/me/notifications/$id/read'
    | '/api/me/plugins/$pluginId/bookmark'
    | '/api/me/plugins/$pluginId/follow'
    | '/api/me/publishers/$publisherId/follow'
    | '/api/ops/approvals/$id/revisions'
    | '/api/ops/users/$id/role'
    | '/api/ops/v1/observations/$observationId'
    | '/api/ops/v1/plugins/$id'
    | '/api/ops/v1/submissions/$id'
    | '/og/plugins/$locale/$slug/card.png'
    | '/api/ops/v1/plugins'
    | '/api/ops/v1/reports'
    | '/api/ops/v1/submissions'
    | '/api/admin/approvals/$id/effects/retry'
    | '/api/me/collections/$id/plugins/$pluginId'
    | '/api/ops/approvals/$id/effects/claim'
    | '/api/ops/approvals/$id/effects/result'
    | '/api/ops/v1/plugins/$id/curation'
    | '/api/ops/v1/plugins/$id/media'
    | '/api/ops/v1/plugins/$id/visibility'
    | '/api/ops/v1/submissions/$id/resolution'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/api-docs.md'
    | '/auth.md'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/examples'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/github-stars'
    | '/api/health'
    | '/$locale/'
    | '/$locale/account/appeals'
    | '/$locale/account/collections'
    | '/$locale/account/notifications'
    | '/$locale/account/settings'
    | '/$locale/account/submissions'
    | '/$locale/auth/cli'
    | '/$locale/categories/$slug'
    | '/$locale/collections/$id'
    | '/$locale/docs/$slug'
    | '/$locale/legal/$document'
    | '/$locale/plugins/$slug'
    | '/$locale/publishers/$login'
    | '/$locale/users/$login'
    | '/.well-known/mcp/server-card.json'
    | '/admin/approvals/$id'
    | '/api/auth/$'
    | '/api/cli/token'
    | '/api/collections/$id'
    | '/api/community/verification'
    | '/api/me/account'
    | '/api/me/profile'
    | '/api/me/relationships'
    | '/api/media/$id'
    | '/api/plugins/$slug'
    | '/api/publishers/$login'
    | '/api/replies/$id'
    | '/api/users/$login'
    | '/$locale/account/'
    | '/$locale/docs/'
    | '/$locale/operations/'
    | '/$locale/plugins/'
    | '/admin/approvals/'
    | '/api/plugins/'
    | '/api/reports/'
    | '/api/submissions/'
    | '/api/admin/approvals/$id'
    | '/api/claims/$id/verify'
    | '/api/marketplace/plugins/$slug'
    | '/api/me/blocks/$userId'
    | '/api/me/collections/$id'
    | '/api/ops/approvals/$id'
    | '/api/ops/moderation/actions'
    | '/api/ops/moderation/queue'
    | '/api/ops/v1/audit'
    | '/api/ops/v1/observations:batch'
    | '/api/ops/v1/status'
    | '/api/plugins/$slug/claims'
    | '/api/plugins/$slug/review'
    | '/api/plugins/$slug/reviews'
    | '/api/reviews/$id/replies'
    | '/og/home/$locale/card.png'
    | '/api/admin/approvals/'
    | '/api/cli/authorizations/'
    | '/api/marketplace/plugins/'
    | '/api/me/appeals/'
    | '/api/me/collections/'
    | '/api/me/notifications/'
    | '/api/me/submissions/'
    | '/api/operations/reports/'
    | '/api/ops/approvals/'
    | '/api/admin/approvals/$id/decisions'
    | '/api/cli/authorizations/$id/approve'
    | '/api/me/notifications/$id/read'
    | '/api/me/plugins/$pluginId/bookmark'
    | '/api/me/plugins/$pluginId/follow'
    | '/api/me/publishers/$publisherId/follow'
    | '/api/ops/approvals/$id/revisions'
    | '/api/ops/users/$id/role'
    | '/api/ops/v1/observations/$observationId'
    | '/api/ops/v1/plugins/$id'
    | '/api/ops/v1/submissions/$id'
    | '/og/plugins/$locale/$slug/card.png'
    | '/api/ops/v1/plugins/'
    | '/api/ops/v1/reports/'
    | '/api/ops/v1/submissions/'
    | '/api/admin/approvals/$id/effects/retry'
    | '/api/me/collections/$id/plugins/$pluginId'
    | '/api/ops/approvals/$id/effects/claim'
    | '/api/ops/approvals/$id/effects/result'
    | '/api/ops/v1/plugins/$id/curation'
    | '/api/ops/v1/plugins/$id/media'
    | '/api/ops/v1/plugins/$id/visibility'
    | '/api/ops/v1/submissions/$id/resolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ApiDocsDotmdRoute: typeof ApiDocsDotmdRoute
  AuthDotmdRoute: typeof AuthDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiGithubStarsRoute: typeof ApiGithubStarsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  AdminApprovalsIdRoute: typeof AdminApprovalsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCliTokenRoute: typeof ApiCliTokenRoute
  ApiCollectionsIdRoute: typeof ApiCollectionsIdRoute
  ApiCommunityVerificationRoute: typeof ApiCommunityVerificationRoute
  ApiMeAccountRoute: typeof ApiMeAccountRoute
  ApiMeProfileRoute: typeof ApiMeProfileRoute
  ApiMeRelationshipsRoute: typeof ApiMeRelationshipsRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiPluginsSlugRoute: typeof ApiPluginsSlugRouteWithChildren
  ApiPublishersLoginRoute: typeof ApiPublishersLoginRoute
  ApiRepliesIdRoute: typeof ApiRepliesIdRoute
  ApiUsersLoginRoute: typeof ApiUsersLoginRoute
  AdminApprovalsIndexRoute: typeof AdminApprovalsIndexRoute
  ApiPluginsIndexRoute: typeof ApiPluginsIndexRoute
  ApiReportsIndexRoute: typeof ApiReportsIndexRoute
  ApiSubmissionsIndexRoute: typeof ApiSubmissionsIndexRoute
  ApiAdminApprovalsIdRoute: typeof ApiAdminApprovalsIdRouteWithChildren
  ApiClaimsIdVerifyRoute: typeof ApiClaimsIdVerifyRoute
  ApiMarketplacePluginsSlugRoute: typeof ApiMarketplacePluginsSlugRoute
  ApiMeBlocksUserIdRoute: typeof ApiMeBlocksUserIdRoute
  ApiMeCollectionsIdRoute: typeof ApiMeCollectionsIdRouteWithChildren
  ApiOpsApprovalsIdRoute: typeof ApiOpsApprovalsIdRouteWithChildren
  ApiOpsModerationActionsRoute: typeof ApiOpsModerationActionsRoute
  ApiOpsModerationQueueRoute: typeof ApiOpsModerationQueueRoute
  ApiOpsV1AuditRoute: typeof ApiOpsV1AuditRoute
  ApiOpsV1ObservationsChar58batchRoute: typeof ApiOpsV1ObservationsChar58batchRoute
  ApiOpsV1StatusRoute: typeof ApiOpsV1StatusRoute
  ApiReviewsIdRepliesRoute: typeof ApiReviewsIdRepliesRoute
  OgHomeLocaleCardDotpngRoute: typeof OgHomeLocaleCardDotpngRoute
  ApiAdminApprovalsIndexRoute: typeof ApiAdminApprovalsIndexRoute
  ApiCliAuthorizationsIndexRoute: typeof ApiCliAuthorizationsIndexRoute
  ApiMarketplacePluginsIndexRoute: typeof ApiMarketplacePluginsIndexRoute
  ApiMeAppealsIndexRoute: typeof ApiMeAppealsIndexRoute
  ApiMeCollectionsIndexRoute: typeof ApiMeCollectionsIndexRoute
  ApiMeNotificationsIndexRoute: typeof ApiMeNotificationsIndexRoute
  ApiMeSubmissionsIndexRoute: typeof ApiMeSubmissionsIndexRoute
  ApiOperationsReportsIndexRoute: typeof ApiOperationsReportsIndexRoute
  ApiOpsApprovalsIndexRoute: typeof ApiOpsApprovalsIndexRoute
  ApiCliAuthorizationsIdApproveRoute: typeof ApiCliAuthorizationsIdApproveRoute
  ApiMeNotificationsIdReadRoute: typeof ApiMeNotificationsIdReadRoute
  ApiMePluginsPluginIdBookmarkRoute: typeof ApiMePluginsPluginIdBookmarkRoute
  ApiMePluginsPluginIdFollowRoute: typeof ApiMePluginsPluginIdFollowRoute
  ApiMePublishersPublisherIdFollowRoute: typeof ApiMePublishersPublisherIdFollowRoute
  ApiOpsUsersIdRoleRoute: typeof ApiOpsUsersIdRoleRoute
  ApiOpsV1ObservationsObservationIdRoute: typeof ApiOpsV1ObservationsObservationIdRoute
  ApiOpsV1PluginsIdRoute: typeof ApiOpsV1PluginsIdRouteWithChildren
  ApiOpsV1SubmissionsIdRoute: typeof ApiOpsV1SubmissionsIdRouteWithChildren
  OgPluginsLocaleSlugCardDotpngRoute: typeof OgPluginsLocaleSlugCardDotpngRoute
  ApiOpsV1PluginsIndexRoute: typeof ApiOpsV1PluginsIndexRoute
  ApiOpsV1ReportsIndexRoute: typeof ApiOpsV1ReportsIndexRoute
  ApiOpsV1SubmissionsIndexRoute: typeof ApiOpsV1SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs.md': {
      id: '/api-docs.md'
      path: '/api-docs.md'
      fullPath: '/api-docs.md'
      preLoaderRoute: typeof ApiDocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/examples': {
      id: '/$locale/examples'
      path: '/examples'
      fullPath: '/$locale/examples'
      preLoaderRoute: typeof LocaleExamplesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-stars': {
      id: '/api/github-stars'
      path: '/api/github-stars'
      fullPath: '/api/github-stars'
      preLoaderRoute: typeof ApiGithubStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/account/': {
      id: '/$locale/account/'
      path: '/account'
      fullPath: '/$locale/account/'
      preLoaderRoute: typeof LocaleAccountIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/appeals': {
      id: '/$locale/account/appeals'
      path: '/account/appeals'
      fullPath: '/$locale/account/appeals'
      preLoaderRoute: typeof LocaleAccountAppealsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/collections': {
      id: '/$locale/account/collections'
      path: '/account/collections'
      fullPath: '/$locale/account/collections'
      preLoaderRoute: typeof LocaleAccountCollectionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/notifications': {
      id: '/$locale/account/notifications'
      path: '/account/notifications'
      fullPath: '/$locale/account/notifications'
      preLoaderRoute: typeof LocaleAccountNotificationsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/settings': {
      id: '/$locale/account/settings'
      path: '/account/settings'
      fullPath: '/$locale/account/settings'
      preLoaderRoute: typeof LocaleAccountSettingsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account/submissions': {
      id: '/$locale/account/submissions'
      path: '/account/submissions'
      fullPath: '/$locale/account/submissions'
      preLoaderRoute: typeof LocaleAccountSubmissionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/cli': {
      id: '/$locale/auth/cli'
      path: '/auth/cli'
      fullPath: '/$locale/auth/cli'
      preLoaderRoute: typeof LocaleAuthCliRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/categories/$slug': {
      id: '/$locale/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/$locale/categories/$slug'
      preLoaderRoute: typeof LocaleCategoriesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/collections/$id': {
      id: '/$locale/collections/$id'
      path: '/collections/$id'
      fullPath: '/$locale/collections/$id'
      preLoaderRoute: typeof LocaleCollectionsIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/docs/': {
      id: '/$locale/docs/'
      path: '/docs'
      fullPath: '/$locale/docs/'
      preLoaderRoute: typeof LocaleDocsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/docs/$slug': {
      id: '/$locale/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/$locale/docs/$slug'
      preLoaderRoute: typeof LocaleDocsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/legal/$document': {
      id: '/$locale/legal/$document'
      path: '/legal/$document'
      fullPath: '/$locale/legal/$document'
      preLoaderRoute: typeof LocaleLegalDocumentRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/operations/': {
      id: '/$locale/operations/'
      path: '/operations'
      fullPath: '/$locale/operations/'
      preLoaderRoute: typeof LocaleOperationsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plugins/': {
      id: '/$locale/plugins/'
      path: '/plugins'
      fullPath: '/$locale/plugins/'
      preLoaderRoute: typeof LocalePluginsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/plugins/$slug': {
      id: '/$locale/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/$locale/plugins/$slug'
      preLoaderRoute: typeof LocalePluginsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/publishers/$login': {
      id: '/$locale/publishers/$login'
      path: '/publishers/$login'
      fullPath: '/$locale/publishers/$login'
      preLoaderRoute: typeof LocalePublishersLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/users/$login': {
      id: '/$locale/users/$login'
      path: '/users/$login'
      fullPath: '/$locale/users/$login'
      preLoaderRoute: typeof LocaleUsersLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals/': {
      id: '/admin/approvals/'
      path: '/admin/approvals'
      fullPath: '/admin/approvals/'
      preLoaderRoute: typeof AdminApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals/$id': {
      id: '/admin/approvals/$id'
      path: '/admin/approvals/$id'
      fullPath: '/admin/approvals/$id'
      preLoaderRoute: typeof AdminApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/token': {
      id: '/api/cli/token'
      path: '/api/cli/token'
      fullPath: '/api/cli/token'
      preLoaderRoute: typeof ApiCliTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/$id': {
      id: '/api/collections/$id'
      path: '/api/collections/$id'
      fullPath: '/api/collections/$id'
      preLoaderRoute: typeof ApiCollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community/verification': {
      id: '/api/community/verification'
      path: '/api/community/verification'
      fullPath: '/api/community/verification'
      preLoaderRoute: typeof ApiCommunityVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/account': {
      id: '/api/me/account'
      path: '/api/me/account'
      fullPath: '/api/me/account'
      preLoaderRoute: typeof ApiMeAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/profile': {
      id: '/api/me/profile'
      path: '/api/me/profile'
      fullPath: '/api/me/profile'
      preLoaderRoute: typeof ApiMeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/relationships': {
      id: '/api/me/relationships'
      path: '/api/me/relationships'
      fullPath: '/api/me/relationships'
      preLoaderRoute: typeof ApiMeRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/': {
      id: '/api/plugins/'
      path: '/api/plugins'
      fullPath: '/api/plugins/'
      preLoaderRoute: typeof ApiPluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/$slug': {
      id: '/api/plugins/$slug'
      path: '/api/plugins/$slug'
      fullPath: '/api/plugins/$slug'
      preLoaderRoute: typeof ApiPluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publishers/$login': {
      id: '/api/publishers/$login'
      path: '/api/publishers/$login'
      fullPath: '/api/publishers/$login'
      preLoaderRoute: typeof ApiPublishersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/replies/$id': {
      id: '/api/replies/$id'
      path: '/api/replies/$id'
      fullPath: '/api/replies/$id'
      preLoaderRoute: typeof ApiRepliesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/': {
      id: '/api/reports/'
      path: '/api/reports'
      fullPath: '/api/reports/'
      preLoaderRoute: typeof ApiReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions/': {
      id: '/api/submissions/'
      path: '/api/submissions'
      fullPath: '/api/submissions/'
      preLoaderRoute: typeof ApiSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$login': {
      id: '/api/users/$login'
      path: '/api/users/$login'
      fullPath: '/api/users/$login'
      preLoaderRoute: typeof ApiUsersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals/': {
      id: '/api/admin/approvals/'
      path: '/api/admin/approvals'
      fullPath: '/api/admin/approvals/'
      preLoaderRoute: typeof ApiAdminApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals/$id': {
      id: '/api/admin/approvals/$id'
      path: '/api/admin/approvals/$id'
      fullPath: '/api/admin/approvals/$id'
      preLoaderRoute: typeof ApiAdminApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claims/$id/verify': {
      id: '/api/claims/$id/verify'
      path: '/api/claims/$id/verify'
      fullPath: '/api/claims/$id/verify'
      preLoaderRoute: typeof ApiClaimsIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/authorizations/': {
      id: '/api/cli/authorizations/'
      path: '/api/cli/authorizations'
      fullPath: '/api/cli/authorizations/'
      preLoaderRoute: typeof ApiCliAuthorizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/plugins/': {
      id: '/api/marketplace/plugins/'
      path: '/api/marketplace/plugins'
      fullPath: '/api/marketplace/plugins/'
      preLoaderRoute: typeof ApiMarketplacePluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/plugins/$slug': {
      id: '/api/marketplace/plugins/$slug'
      path: '/api/marketplace/plugins/$slug'
      fullPath: '/api/marketplace/plugins/$slug'
      preLoaderRoute: typeof ApiMarketplacePluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/appeals/': {
      id: '/api/me/appeals/'
      path: '/api/me/appeals'
      fullPath: '/api/me/appeals/'
      preLoaderRoute: typeof ApiMeAppealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/blocks/$userId': {
      id: '/api/me/blocks/$userId'
      path: '/api/me/blocks/$userId'
      fullPath: '/api/me/blocks/$userId'
      preLoaderRoute: typeof ApiMeBlocksUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/collections/': {
      id: '/api/me/collections/'
      path: '/api/me/collections'
      fullPath: '/api/me/collections/'
      preLoaderRoute: typeof ApiMeCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/collections/$id': {
      id: '/api/me/collections/$id'
      path: '/api/me/collections/$id'
      fullPath: '/api/me/collections/$id'
      preLoaderRoute: typeof ApiMeCollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/notifications/': {
      id: '/api/me/notifications/'
      path: '/api/me/notifications'
      fullPath: '/api/me/notifications/'
      preLoaderRoute: typeof ApiMeNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/submissions/': {
      id: '/api/me/submissions/'
      path: '/api/me/submissions'
      fullPath: '/api/me/submissions/'
      preLoaderRoute: typeof ApiMeSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/reports/': {
      id: '/api/operations/reports/'
      path: '/api/operations/reports'
      fullPath: '/api/operations/reports/'
      preLoaderRoute: typeof ApiOperationsReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/approvals/': {
      id: '/api/ops/approvals/'
      path: '/api/ops/approvals'
      fullPath: '/api/ops/approvals/'
      preLoaderRoute: typeof ApiOpsApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/approvals/$id': {
      id: '/api/ops/approvals/$id'
      path: '/api/ops/approvals/$id'
      fullPath: '/api/ops/approvals/$id'
      preLoaderRoute: typeof ApiOpsApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/moderation/actions': {
      id: '/api/ops/moderation/actions'
      path: '/api/ops/moderation/actions'
      fullPath: '/api/ops/moderation/actions'
      preLoaderRoute: typeof ApiOpsModerationActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/moderation/queue': {
      id: '/api/ops/moderation/queue'
      path: '/api/ops/moderation/queue'
      fullPath: '/api/ops/moderation/queue'
      preLoaderRoute: typeof ApiOpsModerationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/audit': {
      id: '/api/ops/v1/audit'
      path: '/api/ops/v1/audit'
      fullPath: '/api/ops/v1/audit'
      preLoaderRoute: typeof ApiOpsV1AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/observations:batch': {
      id: '/api/ops/v1/observations:batch'
      path: '/api/ops/v1/observations:batch'
      fullPath: '/api/ops/v1/observations:batch'
      preLoaderRoute: typeof ApiOpsV1ObservationsChar58batchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/status': {
      id: '/api/ops/v1/status'
      path: '/api/ops/v1/status'
      fullPath: '/api/ops/v1/status'
      preLoaderRoute: typeof ApiOpsV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugins/$slug/claims': {
      id: '/api/plugins/$slug/claims'
      path: '/claims'
      fullPath: '/api/plugins/$slug/claims'
      preLoaderRoute: typeof ApiPluginsSlugClaimsRouteImport
      parentRoute: typeof ApiPluginsSlugRoute
    }
    '/api/plugins/$slug/review': {
      id: '/api/plugins/$slug/review'
      path: '/review'
      fullPath: '/api/plugins/$slug/review'
      preLoaderRoute: typeof ApiPluginsSlugReviewRouteImport
      parentRoute: typeof ApiPluginsSlugRoute
    }
    '/api/plugins/$slug/reviews': {
      id: '/api/plugins/$slug/reviews'
      path: '/reviews'
      fullPath: '/api/plugins/$slug/reviews'
      preLoaderRoute: typeof ApiPluginsSlugReviewsRouteImport
      parentRoute: typeof ApiPluginsSlugRoute
    }
    '/api/reviews/$id/replies': {
      id: '/api/reviews/$id/replies'
      path: '/api/reviews/$id/replies'
      fullPath: '/api/reviews/$id/replies'
      preLoaderRoute: typeof ApiReviewsIdRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/home/$locale/card.png': {
      id: '/og/home/$locale/card.png'
      path: '/og/home/$locale/card.png'
      fullPath: '/og/home/$locale/card.png'
      preLoaderRoute: typeof OgHomeLocaleCardDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals/$id/decisions': {
      id: '/api/admin/approvals/$id/decisions'
      path: '/decisions'
      fullPath: '/api/admin/approvals/$id/decisions'
      preLoaderRoute: typeof ApiAdminApprovalsIdDecisionsRouteImport
      parentRoute: typeof ApiAdminApprovalsIdRoute
    }
    '/api/cli/authorizations/$id/approve': {
      id: '/api/cli/authorizations/$id/approve'
      path: '/api/cli/authorizations/$id/approve'
      fullPath: '/api/cli/authorizations/$id/approve'
      preLoaderRoute: typeof ApiCliAuthorizationsIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/notifications/$id/read': {
      id: '/api/me/notifications/$id/read'
      path: '/api/me/notifications/$id/read'
      fullPath: '/api/me/notifications/$id/read'
      preLoaderRoute: typeof ApiMeNotificationsIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/plugins/$pluginId/bookmark': {
      id: '/api/me/plugins/$pluginId/bookmark'
      path: '/api/me/plugins/$pluginId/bookmark'
      fullPath: '/api/me/plugins/$pluginId/bookmark'
      preLoaderRoute: typeof ApiMePluginsPluginIdBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/plugins/$pluginId/follow': {
      id: '/api/me/plugins/$pluginId/follow'
      path: '/api/me/plugins/$pluginId/follow'
      fullPath: '/api/me/plugins/$pluginId/follow'
      preLoaderRoute: typeof ApiMePluginsPluginIdFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/publishers/$publisherId/follow': {
      id: '/api/me/publishers/$publisherId/follow'
      path: '/api/me/publishers/$publisherId/follow'
      fullPath: '/api/me/publishers/$publisherId/follow'
      preLoaderRoute: typeof ApiMePublishersPublisherIdFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/approvals/$id/revisions': {
      id: '/api/ops/approvals/$id/revisions'
      path: '/revisions'
      fullPath: '/api/ops/approvals/$id/revisions'
      preLoaderRoute: typeof ApiOpsApprovalsIdRevisionsRouteImport
      parentRoute: typeof ApiOpsApprovalsIdRoute
    }
    '/api/ops/users/$id/role': {
      id: '/api/ops/users/$id/role'
      path: '/api/ops/users/$id/role'
      fullPath: '/api/ops/users/$id/role'
      preLoaderRoute: typeof ApiOpsUsersIdRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/observations/$observationId': {
      id: '/api/ops/v1/observations/$observationId'
      path: '/api/ops/v1/observations/$observationId'
      fullPath: '/api/ops/v1/observations/$observationId'
      preLoaderRoute: typeof ApiOpsV1ObservationsObservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/plugins/': {
      id: '/api/ops/v1/plugins/'
      path: '/api/ops/v1/plugins'
      fullPath: '/api/ops/v1/plugins/'
      preLoaderRoute: typeof ApiOpsV1PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/plugins/$id': {
      id: '/api/ops/v1/plugins/$id'
      path: '/api/ops/v1/plugins/$id'
      fullPath: '/api/ops/v1/plugins/$id'
      preLoaderRoute: typeof ApiOpsV1PluginsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/reports/': {
      id: '/api/ops/v1/reports/'
      path: '/api/ops/v1/reports'
      fullPath: '/api/ops/v1/reports/'
      preLoaderRoute: typeof ApiOpsV1ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/submissions/': {
      id: '/api/ops/v1/submissions/'
      path: '/api/ops/v1/submissions'
      fullPath: '/api/ops/v1/submissions/'
      preLoaderRoute: typeof ApiOpsV1SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/v1/submissions/$id': {
      id: '/api/ops/v1/submissions/$id'
      path: '/api/ops/v1/submissions/$id'
      fullPath: '/api/ops/v1/submissions/$id'
      preLoaderRoute: typeof ApiOpsV1SubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/plugins/$locale/$slug/card.png': {
      id: '/og/plugins/$locale/$slug/card.png'
      path: '/og/plugins/$locale/$slug/card.png'
      fullPath: '/og/plugins/$locale/$slug/card.png'
      preLoaderRoute: typeof OgPluginsLocaleSlugCardDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals/$id/effects/retry': {
      id: '/api/admin/approvals/$id/effects/retry'
      path: '/effects/retry'
      fullPath: '/api/admin/approvals/$id/effects/retry'
      preLoaderRoute: typeof ApiAdminApprovalsIdEffectsRetryRouteImport
      parentRoute: typeof ApiAdminApprovalsIdRoute
    }
    '/api/me/collections/$id/plugins/$pluginId': {
      id: '/api/me/collections/$id/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/api/me/collections/$id/plugins/$pluginId'
      preLoaderRoute: typeof ApiMeCollectionsIdPluginsPluginIdRouteImport
      parentRoute: typeof ApiMeCollectionsIdRoute
    }
    '/api/ops/approvals/$id/effects/claim': {
      id: '/api/ops/approvals/$id/effects/claim'
      path: '/effects/claim'
      fullPath: '/api/ops/approvals/$id/effects/claim'
      preLoaderRoute: typeof ApiOpsApprovalsIdEffectsClaimRouteImport
      parentRoute: typeof ApiOpsApprovalsIdRoute
    }
    '/api/ops/approvals/$id/effects/result': {
      id: '/api/ops/approvals/$id/effects/result'
      path: '/effects/result'
      fullPath: '/api/ops/approvals/$id/effects/result'
      preLoaderRoute: typeof ApiOpsApprovalsIdEffectsResultRouteImport
      parentRoute: typeof ApiOpsApprovalsIdRoute
    }
    '/api/ops/v1/plugins/$id/curation': {
      id: '/api/ops/v1/plugins/$id/curation'
      path: '/curation'
      fullPath: '/api/ops/v1/plugins/$id/curation'
      preLoaderRoute: typeof ApiOpsV1PluginsIdCurationRouteImport
      parentRoute: typeof ApiOpsV1PluginsIdRoute
    }
    '/api/ops/v1/plugins/$id/media': {
      id: '/api/ops/v1/plugins/$id/media'
      path: '/media'
      fullPath: '/api/ops/v1/plugins/$id/media'
      preLoaderRoute: typeof ApiOpsV1PluginsIdMediaRouteImport
      parentRoute: typeof ApiOpsV1PluginsIdRoute
    }
    '/api/ops/v1/plugins/$id/visibility': {
      id: '/api/ops/v1/plugins/$id/visibility'
      path: '/visibility'
      fullPath: '/api/ops/v1/plugins/$id/visibility'
      preLoaderRoute: typeof ApiOpsV1PluginsIdVisibilityRouteImport
      parentRoute: typeof ApiOpsV1PluginsIdRoute
    }
    '/api/ops/v1/submissions/$id/resolution': {
      id: '/api/ops/v1/submissions/$id/resolution'
      path: '/resolution'
      fullPath: '/api/ops/v1/submissions/$id/resolution'
      preLoaderRoute: typeof ApiOpsV1SubmissionsIdResolutionRouteImport
      parentRoute: typeof ApiOpsV1SubmissionsIdRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleExamplesRoute: typeof LocaleExamplesRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAccountAppealsRoute: typeof LocaleAccountAppealsRoute
  LocaleAccountCollectionsRoute: typeof LocaleAccountCollectionsRoute
  LocaleAccountNotificationsRoute: typeof LocaleAccountNotificationsRoute
  LocaleAccountSettingsRoute: typeof LocaleAccountSettingsRoute
  LocaleAccountSubmissionsRoute: typeof LocaleAccountSubmissionsRoute
  LocaleAuthCliRoute: typeof LocaleAuthCliRoute
  LocaleCategoriesSlugRoute: typeof LocaleCategoriesSlugRoute
  LocaleCollectionsIdRoute: typeof LocaleCollectionsIdRoute
  LocaleDocsSlugRoute: typeof LocaleDocsSlugRoute
  LocaleLegalDocumentRoute: typeof LocaleLegalDocumentRoute
  LocalePluginsSlugRoute: typeof LocalePluginsSlugRoute
  LocalePublishersLoginRoute: typeof LocalePublishersLoginRoute
  LocaleUsersLoginRoute: typeof LocaleUsersLoginRoute
  LocaleAccountIndexRoute: typeof LocaleAccountIndexRoute
  LocaleDocsIndexRoute: typeof LocaleDocsIndexRoute
  LocaleOperationsIndexRoute: typeof LocaleOperationsIndexRoute
  LocalePluginsIndexRoute: typeof LocalePluginsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleExamplesRoute: LocaleExamplesRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAccountAppealsRoute: LocaleAccountAppealsRoute,
  LocaleAccountCollectionsRoute: LocaleAccountCollectionsRoute,
  LocaleAccountNotificationsRoute: LocaleAccountNotificationsRoute,
  LocaleAccountSettingsRoute: LocaleAccountSettingsRoute,
  LocaleAccountSubmissionsRoute: LocaleAccountSubmissionsRoute,
  LocaleAuthCliRoute: LocaleAuthCliRoute,
  LocaleCategoriesSlugRoute: LocaleCategoriesSlugRoute,
  LocaleCollectionsIdRoute: LocaleCollectionsIdRoute,
  LocaleDocsSlugRoute: LocaleDocsSlugRoute,
  LocaleLegalDocumentRoute: LocaleLegalDocumentRoute,
  LocalePluginsSlugRoute: LocalePluginsSlugRoute,
  LocalePublishersLoginRoute: LocalePublishersLoginRoute,
  LocaleUsersLoginRoute: LocaleUsersLoginRoute,
  LocaleAccountIndexRoute: LocaleAccountIndexRoute,
  LocaleDocsIndexRoute: LocaleDocsIndexRoute,
  LocaleOperationsIndexRoute: LocaleOperationsIndexRoute,
  LocalePluginsIndexRoute: LocalePluginsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface ApiPluginsSlugRouteChildren {
  ApiPluginsSlugClaimsRoute: typeof ApiPluginsSlugClaimsRoute
  ApiPluginsSlugReviewRoute: typeof ApiPluginsSlugReviewRoute
  ApiPluginsSlugReviewsRoute: typeof ApiPluginsSlugReviewsRoute
}

const ApiPluginsSlugRouteChildren: ApiPluginsSlugRouteChildren = {
  ApiPluginsSlugClaimsRoute: ApiPluginsSlugClaimsRoute,
  ApiPluginsSlugReviewRoute: ApiPluginsSlugReviewRoute,
  ApiPluginsSlugReviewsRoute: ApiPluginsSlugReviewsRoute,
}

const ApiPluginsSlugRouteWithChildren = ApiPluginsSlugRoute._addFileChildren(
  ApiPluginsSlugRouteChildren,
)

interface ApiAdminApprovalsIdRouteChildren {
  ApiAdminApprovalsIdDecisionsRoute: typeof ApiAdminApprovalsIdDecisionsRoute
  ApiAdminApprovalsIdEffectsRetryRoute: typeof ApiAdminApprovalsIdEffectsRetryRoute
}

const ApiAdminApprovalsIdRouteChildren: ApiAdminApprovalsIdRouteChildren = {
  ApiAdminApprovalsIdDecisionsRoute: ApiAdminApprovalsIdDecisionsRoute,
  ApiAdminApprovalsIdEffectsRetryRoute: ApiAdminApprovalsIdEffectsRetryRoute,
}

const ApiAdminApprovalsIdRouteWithChildren =
  ApiAdminApprovalsIdRoute._addFileChildren(ApiAdminApprovalsIdRouteChildren)

interface ApiMeCollectionsIdRouteChildren {
  ApiMeCollectionsIdPluginsPluginIdRoute: typeof ApiMeCollectionsIdPluginsPluginIdRoute
}

const ApiMeCollectionsIdRouteChildren: ApiMeCollectionsIdRouteChildren = {
  ApiMeCollectionsIdPluginsPluginIdRoute:
    ApiMeCollectionsIdPluginsPluginIdRoute,
}

const ApiMeCollectionsIdRouteWithChildren =
  ApiMeCollectionsIdRoute._addFileChildren(ApiMeCollectionsIdRouteChildren)

interface ApiOpsApprovalsIdRouteChildren {
  ApiOpsApprovalsIdRevisionsRoute: typeof ApiOpsApprovalsIdRevisionsRoute
  ApiOpsApprovalsIdEffectsClaimRoute: typeof ApiOpsApprovalsIdEffectsClaimRoute
  ApiOpsApprovalsIdEffectsResultRoute: typeof ApiOpsApprovalsIdEffectsResultRoute
}

const ApiOpsApprovalsIdRouteChildren: ApiOpsApprovalsIdRouteChildren = {
  ApiOpsApprovalsIdRevisionsRoute: ApiOpsApprovalsIdRevisionsRoute,
  ApiOpsApprovalsIdEffectsClaimRoute: ApiOpsApprovalsIdEffectsClaimRoute,
  ApiOpsApprovalsIdEffectsResultRoute: ApiOpsApprovalsIdEffectsResultRoute,
}

const ApiOpsApprovalsIdRouteWithChildren =
  ApiOpsApprovalsIdRoute._addFileChildren(ApiOpsApprovalsIdRouteChildren)

interface ApiOpsV1PluginsIdRouteChildren {
  ApiOpsV1PluginsIdCurationRoute: typeof ApiOpsV1PluginsIdCurationRoute
  ApiOpsV1PluginsIdMediaRoute: typeof ApiOpsV1PluginsIdMediaRoute
  ApiOpsV1PluginsIdVisibilityRoute: typeof ApiOpsV1PluginsIdVisibilityRoute
}

const ApiOpsV1PluginsIdRouteChildren: ApiOpsV1PluginsIdRouteChildren = {
  ApiOpsV1PluginsIdCurationRoute: ApiOpsV1PluginsIdCurationRoute,
  ApiOpsV1PluginsIdMediaRoute: ApiOpsV1PluginsIdMediaRoute,
  ApiOpsV1PluginsIdVisibilityRoute: ApiOpsV1PluginsIdVisibilityRoute,
}

const ApiOpsV1PluginsIdRouteWithChildren =
  ApiOpsV1PluginsIdRoute._addFileChildren(ApiOpsV1PluginsIdRouteChildren)

interface ApiOpsV1SubmissionsIdRouteChildren {
  ApiOpsV1SubmissionsIdResolutionRoute: typeof ApiOpsV1SubmissionsIdResolutionRoute
}

const ApiOpsV1SubmissionsIdRouteChildren: ApiOpsV1SubmissionsIdRouteChildren = {
  ApiOpsV1SubmissionsIdResolutionRoute: ApiOpsV1SubmissionsIdResolutionRoute,
}

const ApiOpsV1SubmissionsIdRouteWithChildren =
  ApiOpsV1SubmissionsIdRoute._addFileChildren(
    ApiOpsV1SubmissionsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ApiDocsDotmdRoute: ApiDocsDotmdRoute,
  AuthDotmdRoute: AuthDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiGithubStarsRoute: ApiGithubStarsRoute,
  ApiHealthRoute: ApiHealthRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  AdminApprovalsIdRoute: AdminApprovalsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCliTokenRoute: ApiCliTokenRoute,
  ApiCollectionsIdRoute: ApiCollectionsIdRoute,
  ApiCommunityVerificationRoute: ApiCommunityVerificationRoute,
  ApiMeAccountRoute: ApiMeAccountRoute,
  ApiMeProfileRoute: ApiMeProfileRoute,
  ApiMeRelationshipsRoute: ApiMeRelationshipsRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiPluginsSlugRoute: ApiPluginsSlugRouteWithChildren,
  ApiPublishersLoginRoute: ApiPublishersLoginRoute,
  ApiRepliesIdRoute: ApiRepliesIdRoute,
  ApiUsersLoginRoute: ApiUsersLoginRoute,
  AdminApprovalsIndexRoute: AdminApprovalsIndexRoute,
  ApiPluginsIndexRoute: ApiPluginsIndexRoute,
  ApiReportsIndexRoute: ApiReportsIndexRoute,
  ApiSubmissionsIndexRoute: ApiSubmissionsIndexRoute,
  ApiAdminApprovalsIdRoute: ApiAdminApprovalsIdRouteWithChildren,
  ApiClaimsIdVerifyRoute: ApiClaimsIdVerifyRoute,
  ApiMarketplacePluginsSlugRoute: ApiMarketplacePluginsSlugRoute,
  ApiMeBlocksUserIdRoute: ApiMeBlocksUserIdRoute,
  ApiMeCollectionsIdRoute: ApiMeCollectionsIdRouteWithChildren,
  ApiOpsApprovalsIdRoute: ApiOpsApprovalsIdRouteWithChildren,
  ApiOpsModerationActionsRoute: ApiOpsModerationActionsRoute,
  ApiOpsModerationQueueRoute: ApiOpsModerationQueueRoute,
  ApiOpsV1AuditRoute: ApiOpsV1AuditRoute,
  ApiOpsV1ObservationsChar58batchRoute: ApiOpsV1ObservationsChar58batchRoute,
  ApiOpsV1StatusRoute: ApiOpsV1StatusRoute,
  ApiReviewsIdRepliesRoute: ApiReviewsIdRepliesRoute,
  OgHomeLocaleCardDotpngRoute: OgHomeLocaleCardDotpngRoute,
  ApiAdminApprovalsIndexRoute: ApiAdminApprovalsIndexRoute,
  ApiCliAuthorizationsIndexRoute: ApiCliAuthorizationsIndexRoute,
  ApiMarketplacePluginsIndexRoute: ApiMarketplacePluginsIndexRoute,
  ApiMeAppealsIndexRoute: ApiMeAppealsIndexRoute,
  ApiMeCollectionsIndexRoute: ApiMeCollectionsIndexRoute,
  ApiMeNotificationsIndexRoute: ApiMeNotificationsIndexRoute,
  ApiMeSubmissionsIndexRoute: ApiMeSubmissionsIndexRoute,
  ApiOperationsReportsIndexRoute: ApiOperationsReportsIndexRoute,
  ApiOpsApprovalsIndexRoute: ApiOpsApprovalsIndexRoute,
  ApiCliAuthorizationsIdApproveRoute: ApiCliAuthorizationsIdApproveRoute,
  ApiMeNotificationsIdReadRoute: ApiMeNotificationsIdReadRoute,
  ApiMePluginsPluginIdBookmarkRoute: ApiMePluginsPluginIdBookmarkRoute,
  ApiMePluginsPluginIdFollowRoute: ApiMePluginsPluginIdFollowRoute,
  ApiMePublishersPublisherIdFollowRoute: ApiMePublishersPublisherIdFollowRoute,
  ApiOpsUsersIdRoleRoute: ApiOpsUsersIdRoleRoute,
  ApiOpsV1ObservationsObservationIdRoute:
    ApiOpsV1ObservationsObservationIdRoute,
  ApiOpsV1PluginsIdRoute: ApiOpsV1PluginsIdRouteWithChildren,
  ApiOpsV1SubmissionsIdRoute: ApiOpsV1SubmissionsIdRouteWithChildren,
  OgPluginsLocaleSlugCardDotpngRoute: OgPluginsLocaleSlugCardDotpngRoute,
  ApiOpsV1PluginsIndexRoute: ApiOpsV1PluginsIndexRoute,
  ApiOpsV1ReportsIndexRoute: ApiOpsV1ReportsIndexRoute,
  ApiOpsV1SubmissionsIndexRoute: ApiOpsV1SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
