export const dailyOperationsPolicy = {
  schemaVersion: 1,
  runLimits: {
    maximumDurationMinutes: 90,
    minimumProcessedItemsWhenAvailable: 5,
    maximumProcessedItems: 10,
    maximumRetriesPerItem: 1,
  },
  discovery: {
    providers: ["github", "npm"],
    lookbackHours: 72,
    publicDataOnly: true,
    installOrExecuteThirdPartyCode: false,
    firstRunFallbackHours: 72,
    deduplicateBy: {
      github:
        "canonical repository identity: repository ID, with lower-cased owner/name as the fallback",
      npm: "canonical lower-cased package name",
    },
  },
  workflow: [
    "submissions",
    "catalog-completeness",
    "catalog-refresh",
    "discovery",
    "audit",
    "report-publish",
  ],
  workAllocation: {
    completenessItemsBeforeDiscovery: 10,
    maximumDiscoveryItemsWhileCompletenessBacklogExists: 0,
    completenessNeeds: ["readme", "publisher", "target", "content"],
    qualityFirst:
      "Finish each selected item through source inspection, fact upsert, bilingual curation, and final needs verification before using another item slot.",
  },
  itemAccounting:
    "Count each canonical submission, discovered identity, refreshed plugin, and acted-on audit finding once, regardless of command count or duplicate query hits.",
  pluginAdmission: {
    lifecycle: ["draft", "published", "hidden"],
    migration: {
      keepPublishedPluginsPublished: true,
      historicalCandidatesBecome: "draft",
    },
    legacyObservationStatusesAcceptedButIgnored: ["confirmed", "candidate"],
    upsertMeaning:
      "The Agent has decided the source represents a plugin; the Hub must not repeat an evidence gate.",
    publishRequirements: [
      "stable identity",
      "display name",
      "version",
      "source",
      "original README collection result",
      "GitHub publisher identity and avatar when a repository owner is available",
      "one unambiguous structurally safe installation target",
      "English and Chinese display names",
      "English and Chinese short descriptions",
      "English and Chinese overviews",
      "sourceReadmeHash matching the current original README when it is available",
      "at least one category",
      "source citations in derivedFrom",
    ],
    nonBlockingInformation: [
      "ordinary risk",
      "unverified status",
      "unknown compatibility",
      "known incompatibility",
      "archived repository",
      "deprecated package",
    ],
    structuralBlocks: [
      "missing installation target",
      "multiple installation targets that cannot be disambiguated",
      "identity conflict",
      "command injection or an equivalent structural hazard in the installation description",
    ],
    automaticHideReasons: [
      "explicitly malicious",
      "impersonation",
      "definitely not a plugin",
      "documented compliance takedown",
    ],
    trustLabels: ["Official", "Community"],
    legacyNonOfficialVerifiedLabel: "Community",
  },
  installation: {
    appliesToAllHubDrivenDownloadsAndInstalls: true,
    requiresSecondConfirmation: true,
    fixedRiskStatement: {
      en: "DSHX Hub only catalogs and organizes plugin metadata. It does not verify security, compatibility, or operability. Downloading or installing is at your own risk.",
      zh: "DSHX Hub 只收录和整理插件元信息，不验证安全性、兼容性或可运行性。下载或安装的风险由你自行承担。",
    },
    hardBlocks: [
      "missing installation target",
      "multiple installation targets that cannot be disambiguated",
      "identity conflict",
      "command injection or an equivalent structural hazard in the installation description",
    ],
  },
  provenance: {
    translationAndSummarizationAllowed: true,
    derivedFactsRequireDerivedFrom: true,
    inventedFactsAllowed: false,
    preserveOriginalReadme: true,
    originalReadmeRendering: "escaped plain text",
    refreshCurationWhenReadmeHashChanges: true,
    collectPublicPublisherAvatar: true,
  },
  curationQuality: {
    forbiddenGenericPlaceholders: true,
    overviewMustCoverWhenSourced: [
      "what the plugin does",
      "core capabilities",
      "configuration or usage",
      "important limitations or operational risks",
    ],
    acceptSubmissionOnlyAfter: [
      "the original README collection result is stored",
      "the public publisher profile and avatar are stored when GitHub supplies them",
      "exactly one unambiguous structurally safe installation target is available",
      "English and Chinese overviews cite and match the current README hash",
    ],
    confirmInferredNpmTargetWithRegistryInspection: true,
  },
  failureHandling: {
    retryItemAtMostOnce: true,
    sourceFailure: "retry once, then skip and record it in the report",
    authenticationFailure: "stop the run immediately",
    hubUnavailable: "stop the run immediately",
    publishPartialWhenHubReachable: true,
    partialTriggers: [
      "a source or item remains skipped after its retry",
      "the 90 minute limit is reached",
      "a selected item remains incomplete",
      "audit or report publication remains incomplete",
    ],
  },
  report: {
    maximumCharactersPerLocale: 10_000,
    format: "plain-text",
    languages: ["en", "zh"],
    forbiddenContent: [
      "tokens or credentials",
      "email addresses",
      "private network addresses or private URLs",
      "local file paths",
      "raw stack traces",
    ],
  },
} as const;
