import type { DailyOperationsScenario } from "../contracts.js";

export const dailyOperationsScenarios = [
  {
    schemaVersion: 1,
    id: "complete-mock-hub-run",
    title: "The final prompt completes the whole mock-Hub workflow",
    given: [
      "The latest report supplies a previous completedAt boundary.",
      "GitHub and npm discovery each return a new plugin plus one cross-query duplicate.",
      "A queued submission resolves to one of the discovered identities.",
      "One draft needs bilingual content, one published plugin needs refresh, and audit returns a reviewable finding.",
    ],
    expectedCommands: [
      "report latest",
      "submission list",
      "submission get",
      "source discover",
      "source inspect",
      "plugin list",
      "plugin get",
      "plugin upsert",
      "plugin curate",
      "submission resolve",
      "audit",
      "report publish",
    ],
    expectedOutcomes: [
      "The Agent selects 5 to 10 canonical items and finishes each one before consuming another item slot.",
      "Discovery starts 72 hours before the previous completedAt and follows pagination only while a full item can still fit in the run budget.",
      "Canonical GitHub and npm identities are deduplicated before inspection.",
      "The database receives idempotent observations, sourced curation, an atomic submission resolution, and one immutable bilingual report.",
      "The public report contains no internal audit data or executable third-party content.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "catalog-backlog-precedes-discovery",
    title: "Incomplete catalog records cannot be starved by discovery",
    given: [
      "Existing plugins still need original README, publisher avatar, exact target, or sourced bilingual content.",
      "Proactive GitHub and npm discovery also has more results than the daily item budget can finish.",
    ],
    expectedCommands: [
      "plugin list",
      "plugin get",
      "source inspect",
      "plugin upsert",
      "plugin curate",
      "source discover",
      "report publish",
    ],
    expectedOutcomes: [
      "The Agent selects 5 incomplete canonical plugins first and may expand the quality batch to at most 10.",
      "Discovery consumes no item slots while any completeness backlog remains.",
      "Each completed plugin has no readme, publisher, target, or content need.",
    ],
    expectedReportStatus: "partial",
  },
  {
    schemaVersion: 1,
    id: "github-discovery-publishes-complete-plugin",
    title: "A GitHub result becomes a published plugin",
    given: [
      "Discovery returns one new canonical GitHub repository.",
      "Inspection proves it is a plugin and returns one structurally safe installation target.",
      "Public sources support all required bilingual curation fields and derivedFrom citations.",
    ],
    expectedCommands: [
      "source discover",
      "source inspect",
      "plugin upsert",
      "plugin get",
      "plugin curate",
      "report publish",
    ],
    expectedOutcomes: [
      "The Agent omits legacy confirmed or candidate product state from the observation.",
      "The upsert creates a draft and curation automatically makes it publishable.",
      "The report names the discovery without claiming the Hub verified safety or compatibility.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "npm-query-overlap-is-deduplicated",
    title: "Repeated npm hits count once",
    given: [
      "The same npm package appears in several discovery queries and pages.",
      "The package also produces an observation already accepted in this run.",
    ],
    expectedCommands: [
      "source discover",
      "source inspect",
      "plugin upsert",
      "report publish",
    ],
    expectedOutcomes: [
      "The lower-cased canonical npm package identity is processed once.",
      "A repeated observation is treated as an idempotent unchanged result.",
      "The item budget increases once for the canonical package.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "submission-is-accepted-atomically",
    title: "A queued submission is inspected and accepted",
    given: [
      "A queued submission links to a public plugin source.",
      "The source resolves to a new canonical plugin identity.",
    ],
    expectedCommands: [
      "submission list",
      "submission get",
      "source inspect",
      "plugin upsert",
      "plugin curate",
      "submission resolve",
      "report publish",
    ],
    expectedOutcomes: [
      "The submission is resolved as accepted only after the plugin write succeeds.",
      "The stored plugin includes the original README collection result and public GitHub publisher avatar facts.",
      "The stored plugin has exactly one available unambiguous structurally safe installation target.",
      "The bilingual overviews match the stored sourceReadmeHash and describe sourced capabilities rather than a generic catalog placeholder.",
      "A final plugin get has no readme, publisher, target, or content need before acceptance.",
      "The resulting plugin ID is included in the resolution.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "ordinary-risk-remains-visible",
    title: "Ordinary risk does not become a verification gate",
    given: [
      "A plugin is archived, deprecated, incompatible, unverified, or has unknown compatibility.",
      "Its identity and one installation target are structurally safe and unambiguous.",
    ],
    expectedCommands: ["plugin get", "plugin curate", "report publish"],
    expectedOutcomes: [
      "The risk is presented as sourced information.",
      "The plugin is not hidden and the ordinary risk does not block publication.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "structural-install-hazard-blocks-publication",
    title: "An unsafe installation description stays draft",
    given: [
      "A source has a missing or ambiguous target, identity conflict, or command-injection structure.",
    ],
    expectedCommands: [
      "source inspect",
      "plugin upsert",
      "plugin get",
      "report publish",
    ],
    expectedOutcomes: [
      "Safe source facts may be retained in draft.",
      "Curation does not publish the plugin until the structural block is repaired.",
      "No third-party command is executed to test the target.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "malicious-plugin-is-hidden",
    title: "Explicit malicious evidence permits automatic hiding",
    given: [
      "Public evidence explicitly establishes malicious behavior or impersonation.",
      "The evidence URL is safe to preserve as provenance.",
    ],
    expectedCommands: ["plugin get", "plugin hide", "report publish"],
    expectedOutcomes: [
      "The plugin is hidden with a concise evidence-based audit reason.",
      "The report describes the action without exposing internal audit payloads.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "source-failure-publishes-partial-report",
    title: "A persistent source failure is skipped",
    given: [
      "One GitHub or npm item fails with a retryable source error twice.",
      "The Hub remains authenticated and reachable.",
    ],
    expectedCommands: [
      "source discover",
      "source inspect",
      "audit",
      "report publish",
    ],
    expectedOutcomes: [
      "The item is attempted initially and retried once only.",
      "Other independent items continue.",
      "The skipped item and sanitized error are included in the report.",
    ],
    expectedReportStatus: "partial",
  },
  {
    schemaVersion: 1,
    id: "run-limit-publishes-partial-report",
    title: "The run stops at its bounded budget",
    given: [
      "The run reaches 90 minutes before one of its selected 5 to 10 canonical items finishes.",
      "The Hub remains authenticated and reachable.",
    ],
    expectedCommands: ["report publish"],
    expectedOutcomes: [
      "No new item is started after either limit is reached.",
      "Completed work, remaining scope, and the limit are summarized without secrets.",
    ],
    expectedReportStatus: "partial",
  },
  {
    schemaVersion: 1,
    id: "hub-authentication-failure-stops-run",
    title: "Hub authentication failure is terminal",
    given: ["A Hub operation returns an authentication failure."],
    expectedCommands: ["report latest"],
    expectedOutcomes: [
      "The run stops immediately instead of retrying unrelated mutations.",
      "No report is published because protected Hub access is unavailable.",
      "No credential value is printed or persisted in a fixture.",
    ],
    expectedReportStatus: "not-published",
  },
  {
    schemaVersion: 1,
    id: "report-run-id-is-idempotent",
    title: "Report publication is safe to repeat",
    given: [
      "The first publish response is lost after the Hub stores the report.",
      "The Agent still has the exact same immutable report input.",
    ],
    expectedCommands: ["report publish"],
    expectedOutcomes: [
      "One retry with the same runId and identical content succeeds idempotently.",
      "Different content for the same runId is treated as idempotency_conflict and is not overwritten.",
    ],
    expectedReportStatus: "completed",
  },
  {
    schemaVersion: 1,
    id: "report-content-is-sanitized",
    title: "Sensitive operational details never enter the public report",
    given: [
      "A source error contains a token, email address, private URL, local path, and raw stack trace.",
      "The Hub remains authenticated and reachable.",
    ],
    expectedCommands: ["report publish"],
    expectedOutcomes: [
      "The report retains only a concise source identity, stable error code, and safe summary.",
      "Secrets, personal contact details, private addresses, local paths, stack frames, and internal audit payloads are removed.",
    ],
    expectedReportStatus: "partial",
  },
] as const satisfies readonly DailyOperationsScenario[];
